version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - run: echo "Installing dependencies"
      - run: npm install
      - run: echo "Building..."
      - run: npm run build
  test:
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - run: echo "Tests"
      - run: npm install
      - run: npm run test
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test